#!/bin/sh
#
# Configure options script for re-calling MagickCore compilation options
# required to use the MagickCore library.
#

prefix=/Sources/dava.framework/Libs/ImageMagick-6.6.9
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/ImageMagick

usage="\
Usage: Magick-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      echo "Example: gcc \`Magick-config --cflags --cppflags\` -o core core.c \`Magick-config --ldflags --libs\`" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac
  case $1 in
    --prefix=*)
      prefix=$optarg
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo '6.6.9 Q16 '
      ;;
    --cflags)
      echo "-I${includedir} "
      ;;
    --cxxflags)
      echo '-g -O2 -D_THREAD_SAFE -pthread'
      ;;
    --cppflags)
      echo '-I/Sources/dava.framework/Libs/ImageMagick-6.6.9/include/ImageMagick'
      ;;
    --ldflags)
      echo '-L/Sources/dava.framework/Libs/ImageMagick-6.6.9/lib -L/Sources/dava.framework/Libs/ImageMagick-6.6.9-0/delegates/lib'
      ;;
    --libs)
      echo "-L${libdir} -lMagickCore -lpng -lbz2 -lz -lm -lpthread "
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
